### ISSUE TITLE
RBE files

### ISSUE THREAD

**Issue by lauratssnt** [pytrip/pytripgui#61]
Hi,
After dose calculation with biological optimization, we end up with a long list of errors - this type

<E> RBEEval: Z=3 A=7: no such projectile
<E> trprbe.c(EffectClassic): no such projectile
<E> trprbe.c(Effect): no such projectile
<E> trpopt.c(H2ODose): RBE calculation failed
<E> RBEEval: Z=3 A=7: no such projectile
<E> trprbe.c(EffectClassic): no such projectile
<E> trprbe.c(Effect): no such projectile
<E> trpopt.c(H2ODose): RBE calculation failed

Seems that our .rbe files for target and surrounding tissues are not valid. 
Is it possible to obtain .rbe files for specific alpha/beta ratio ?

Thanks!

**Comment by nbassler** [comment]
This looks like a TRiP issue rather than PyTRiPGUI. 

Guess you have used some .spc files which contains projectiles which are missing in your .rbe file you loaded. 

Note, the .rbe files are not distributed by PyTRiP(GUI). They are only distributed from GSI, you should contact the TRiP developers Michael Krämer or Michael Scholz regarding this.
